### Makefile -- Rashell library

# Rashell (https://github.com/michipili/rashell)
# This file is part of Rashell
#
# Copyright © 2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		rashell

SRCS=			rashell_Command.ml
SRCS+=			rashell_Timestamp.ml
SRCS+=			rashell_Configuration.ml
SRCS+=			rashell_Posix.ml
SRCS+=			rashell_Mktemp.ml
SRCS+=			rashell_Broken.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
